# put your secret values and credentials here. do not share this file and do not push it to github
api_secret_key = "Z2F1cmF2LmFnZ2Fyd2FsQGFwcGR5bmFtaWNzLmNvbTptbXp0bDhja3Q4MXMxNjZ1b2U1dmQxNm9kbWY5YnVreg==" # please set me up!

[destination.mssql.credentials]
database = "thousand_eyes" # please set me up!
password = "YourStrongPassword" # please set me up!
username = "sa" # please set me up!
host = "localhost" # please set me up!
port = 1433
connect_timeout = 15
# odbc_driver = "odbc_driver" # please set me up!
